// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SocketMessage struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocketMessage) Reset()         { *m = SocketMessage{} }
func (m *SocketMessage) String() string { return proto.CompactTextString(m) }
func (*SocketMessage) ProtoMessage()    {}
func (*SocketMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *SocketMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocketMessage.Unmarshal(m, b)
}
func (m *SocketMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocketMessage.Marshal(b, m, deterministic)
}
func (m *SocketMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocketMessage.Merge(m, src)
}
func (m *SocketMessage) XXX_Size() int {
	return xxx_messageInfo_SocketMessage.Size(m)
}
func (m *SocketMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SocketMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SocketMessage proto.InternalMessageInfo

func (m *SocketMessage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SocketMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SocketMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func init() {
	proto.RegisterType((*SocketMessage)(nil), "protobuf.SocketMessage")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0x81, 0x5c, 0xbc,
	0xc1, 0xf9, 0xc9, 0xd9, 0xa9, 0x25, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x42, 0x5c,
	0x2c, 0x25, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x04,
	0x17, 0x7b, 0x2e, 0x44, 0x5a, 0x82, 0x09, 0x2c, 0x0c, 0xe3, 0x82, 0x54, 0xa7, 0x15, 0xe5, 0xe7,
	0x4a, 0x30, 0x43, 0x54, 0x83, 0xd8, 0x49, 0x6c, 0x60, 0xc3, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x82, 0x71, 0x3e, 0x0f, 0x70, 0x00, 0x00, 0x00,
}
