// Code generated by protoc-gen-go. DO NOT EDIT.
// source: req.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SocketRequest struct {
	Seq                  string   `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Cmd                  string   `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocketRequest) Reset()         { *m = SocketRequest{} }
func (m *SocketRequest) String() string { return proto.CompactTextString(m) }
func (*SocketRequest) ProtoMessage()    {}
func (*SocketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{0}
}

func (m *SocketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocketRequest.Unmarshal(m, b)
}
func (m *SocketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocketRequest.Marshal(b, m, deterministic)
}
func (m *SocketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocketRequest.Merge(m, src)
}
func (m *SocketRequest) XXX_Size() int {
	return xxx_messageInfo_SocketRequest.Size(m)
}
func (m *SocketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SocketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SocketRequest proto.InternalMessageInfo

func (m *SocketRequest) GetSeq() string {
	if m != nil {
		return m.Seq
	}
	return ""
}

func (m *SocketRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *SocketRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SocketLogin struct {
	ServiceToken         string   `protobuf:"bytes,1,opt,name=serviceToken,proto3" json:"serviceToken,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocketLogin) Reset()         { *m = SocketLogin{} }
func (m *SocketLogin) String() string { return proto.CompactTextString(m) }
func (*SocketLogin) ProtoMessage()    {}
func (*SocketLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{1}
}

func (m *SocketLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocketLogin.Unmarshal(m, b)
}
func (m *SocketLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocketLogin.Marshal(b, m, deterministic)
}
func (m *SocketLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocketLogin.Merge(m, src)
}
func (m *SocketLogin) XXX_Size() int {
	return xxx_messageInfo_SocketLogin.Size(m)
}
func (m *SocketLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_SocketLogin.DiscardUnknown(m)
}

var xxx_messageInfo_SocketLogin proto.InternalMessageInfo

func (m *SocketLogin) GetServiceToken() string {
	if m != nil {
		return m.ServiceToken
	}
	return ""
}

func (m *SocketLogin) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SocketLogin) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type SocketHeartBeat struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocketHeartBeat) Reset()         { *m = SocketHeartBeat{} }
func (m *SocketHeartBeat) String() string { return proto.CompactTextString(m) }
func (*SocketHeartBeat) ProtoMessage()    {}
func (*SocketHeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{2}
}

func (m *SocketHeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocketHeartBeat.Unmarshal(m, b)
}
func (m *SocketHeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocketHeartBeat.Marshal(b, m, deterministic)
}
func (m *SocketHeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocketHeartBeat.Merge(m, src)
}
func (m *SocketHeartBeat) XXX_Size() int {
	return xxx_messageInfo_SocketHeartBeat.Size(m)
}
func (m *SocketHeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_SocketHeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_SocketHeartBeat proto.InternalMessageInfo

func (m *SocketHeartBeat) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func init() {
	proto.RegisterType((*SocketRequest)(nil), "protobuf.SocketRequest")
	proto.RegisterType((*SocketLogin)(nil), "protobuf.SocketLogin")
	proto.RegisterType((*SocketHeartBeat)(nil), "protobuf.SocketHeartBeat")
}

func init() { proto.RegisterFile("req.proto", fileDescriptor_a52bd445c288993d) }

var fileDescriptor_a52bd445c288993d = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x4a, 0x2d, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0xee, 0x5c, 0xbc,
	0xc1, 0xf9, 0xc9, 0xd9, 0xa9, 0x25, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x02, 0x5c,
	0xcc, 0xc5, 0xa9, 0x85, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0x26, 0x48, 0x24, 0x39,
	0x37, 0x45, 0x82, 0x09, 0x22, 0x92, 0x9c, 0x9b, 0x22, 0x24, 0xc4, 0xc5, 0x92, 0x92, 0x58, 0x92,
	0x28, 0xc1, 0x0c, 0x16, 0x02, 0xb3, 0x95, 0x22, 0xb9, 0xb8, 0x21, 0x06, 0xf9, 0xe4, 0xa7, 0x67,
	0xe6, 0x09, 0x29, 0x71, 0xf1, 0x14, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x86, 0xe4, 0x67, 0xa7,
	0xe6, 0x41, 0xcd, 0x43, 0x11, 0x13, 0x12, 0xe1, 0x62, 0x4d, 0x2c, 0x28, 0xf0, 0x84, 0x19, 0x0d,
	0xe1, 0x80, 0xac, 0x2b, 0xcd, 0x4c, 0x81, 0x9a, 0x0d, 0x62, 0x2a, 0x29, 0x73, 0xf1, 0x43, 0x8c,
	0xf6, 0x48, 0x4d, 0x2c, 0x2a, 0x71, 0x4a, 0x4d, 0x2c, 0x81, 0x29, 0x62, 0x84, 0x2b, 0x4a, 0x62,
	0x03, 0x7b, 0xc9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x94, 0x7e, 0x2b, 0x92, 0xe6, 0x00, 0x00,
	0x00,
}
