// Code generated by protoc-gen-go. DO NOT EDIT.
// source: res.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SocketResponseHead struct {
	Seq                  string          `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Cmd                  string          `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Response             *SocketResponse `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SocketResponseHead) Reset()         { *m = SocketResponseHead{} }
func (m *SocketResponseHead) String() string { return proto.CompactTextString(m) }
func (*SocketResponseHead) ProtoMessage()    {}
func (*SocketResponseHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{0}
}

func (m *SocketResponseHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocketResponseHead.Unmarshal(m, b)
}
func (m *SocketResponseHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocketResponseHead.Marshal(b, m, deterministic)
}
func (m *SocketResponseHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocketResponseHead.Merge(m, src)
}
func (m *SocketResponseHead) XXX_Size() int {
	return xxx_messageInfo_SocketResponseHead.Size(m)
}
func (m *SocketResponseHead) XXX_DiscardUnknown() {
	xxx_messageInfo_SocketResponseHead.DiscardUnknown(m)
}

var xxx_messageInfo_SocketResponseHead proto.InternalMessageInfo

func (m *SocketResponseHead) GetSeq() string {
	if m != nil {
		return m.Seq
	}
	return ""
}

func (m *SocketResponseHead) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *SocketResponseHead) GetResponse() *SocketResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type SocketResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Result               []byte   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocketResponse) Reset()         { *m = SocketResponse{} }
func (m *SocketResponse) String() string { return proto.CompactTextString(m) }
func (*SocketResponse) ProtoMessage()    {}
func (*SocketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{1}
}

func (m *SocketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocketResponse.Unmarshal(m, b)
}
func (m *SocketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocketResponse.Marshal(b, m, deterministic)
}
func (m *SocketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocketResponse.Merge(m, src)
}
func (m *SocketResponse) XXX_Size() int {
	return xxx_messageInfo_SocketResponse.Size(m)
}
func (m *SocketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SocketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SocketResponse proto.InternalMessageInfo

func (m *SocketResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SocketResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SocketResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*SocketResponseHead)(nil), "protobuf.SocketResponseHead")
	proto.RegisterType((*SocketResponse)(nil), "protobuf.SocketResponse")
}

func init() { proto.RegisterFile("res.proto", fileDescriptor_36bffc8626f07b47) }

var fileDescriptor_36bffc8626f07b47 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x4a, 0x2d, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0x79, 0x5c, 0x42,
	0xc1, 0xf9, 0xc9, 0xd9, 0xa9, 0x25, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x1e, 0xa9,
	0x89, 0x29, 0x42, 0x02, 0x5c, 0xcc, 0xc5, 0xa9, 0x85, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41,
	0x20, 0x26, 0x48, 0x24, 0x39, 0x37, 0x45, 0x82, 0x09, 0x22, 0x92, 0x9c, 0x9b, 0x22, 0x64, 0xc2,
	0xc5, 0x51, 0x04, 0xd5, 0x23, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa1, 0x07, 0x33, 0x56,
	0x0f, 0xd5, 0xcc, 0x20, 0xb8, 0x4a, 0x25, 0x3f, 0x2e, 0x3e, 0x54, 0x39, 0x21, 0x21, 0x2e, 0x96,
	0xe4, 0xfc, 0x94, 0x54, 0xb0, 0x65, 0xbc, 0x41, 0x60, 0x36, 0xc8, 0xb6, 0xdc, 0xe2, 0x74, 0x98,
	0x6d, 0xb9, 0xc5, 0xe9, 0x42, 0x62, 0x5c, 0x6c, 0x45, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x60, 0xbb,
	0x78, 0x82, 0xa0, 0xbc, 0x24, 0x36, 0xb0, 0x95, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed,
	0x00, 0xf9, 0xcd, 0xdd, 0x00, 0x00, 0x00,
}
